//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int MaBaiViet { get; set; }
        public string TieuDe { get; set; }
        public string HinhAnhBaiViet { get; set; }
        public Nullable<System.DateTime> NgayDangBaiViet { get; set; }
        public string NoiDung { get; set; }
        public string MoTa { get; set; }
    }
}
