//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KichThuoc
    {
        public KichThuoc()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int MaSize { get; set; }
        public string TenSize { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
