//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.HinhAnh = new HashSet<HinhAnh>();
            this.KichThuoc = new HashSet<KichThuoc>();
            this.MauSac = new HashSet<MauSac>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaSP { get; set; }
        public Nullable<int> GiaKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string MoTa { get; set; }
        public string HinhAnhSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaDanhMucSP { get; set; }
        public Nullable<int> MaHang { get; set; }
        public Nullable<int> MaBST { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        public virtual BoSuuTap BoSuuTap { get; set; }
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
        public virtual Hang Hang { get; set; }
        public virtual ICollection<HinhAnh> HinhAnh { get; set; }
        public virtual ICollection<KichThuoc> KichThuoc { get; set; }
        public virtual ICollection<MauSac> MauSac { get; set; }
    }
}
